name: Build libtea

on: [push]

defaults:
 run:
  working-directory: ./libtea    

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt install gcc make linux-headers-$(uname -r)
    - name: make
      run: make libtea-x86-paging