name: Build libtea with SGX

on: [pull_request]

defaults:
 run:
  working-directory: ./libtea    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install SGX dependencies
      run: |
          sudo apt install gcc make linux-headers-$(uname -r)
          git submodule init
          git submodule update
          bash -x ./install_libtea_sgx.sh
    - name: make
      run: | 
           source /opt/intel/sgxsdk/environment
           sudo service aesmd status
           make libtea-x86-enclave

  test-paging:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt install gcc make linux-headers-$(uname -r)
    - name: make
      run: make libtea-x86-paging
    - name: load driver
      run: sudo insmod module/libtea.ko
    - name: run basic tests (some functions will fail due to VM restrictions)
      run: sudo ./tests/test-basic
    - name: run cache tests
      run: sudo ./tests/test-cache
    - name: run paging tests
      run: sudo ./tests/utest-paging/utest-paging
